# Generated by Django 5.2.1 on 2025-05-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size_string',
        ),
    ]
