# Generated by Django 5.2.1 on 2025-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
